# please refer to the datura documentation for a full list of configurable settings
# any custom settings you create here will be accessible in instances of classes
# like FileTei and TeiToEs ( @options["setting_name"] )
# you may also create new environments

# please put any sensitive information or computer specific settings in private.yml!

default:
  # please fill in the name of your collection here
  # collection:

  data_base: https://cdrhmedia.unl.edu  # (do not include /data/ in path)
  media_base: https://cdrhmedia.unl.edu

  # refer to the documentation for details about overriding the XSL
  # html_html_xsl:
  # tei_html_xsl: scripts/xslt/tei.xsl
  # vra_html_xsl:

  variables_html:
    site_url: override_in_public
    image_large: 800
    image_thumb: 150

development:
  es_index: edit_public_config
  es_path: https://edit_public_config/elastic
  data_base: https://override_public

data-tei:
  tei_html_xsl: scripts/overrides/cdrh/data-tei.xsl

data-tei-wrap:
  tei_html_xsl: scripts/overrides/cdrh/data-tei-wrap.xsl

teic-html:
  tei_html_xsl: scripts/overrides/tei-c/html/html.xsl

teic-html5:
  tei_html_xsl: scripts/overrides/tei-c/html5/html5.xsl

teic-markdown:
  tei_html_xsl: scripts/overrides/tei-c/markdown/tei-to-markdown.xsl

teic-text:
  tei_html_xsl: scripts/overrides/tei-c/txt/tei-to-text.xsl







# production:
  # limit processed files by adding allowed ids on newlines in a file
  # allowed_files: config/allowed.txt

